// packages/react/src/chord-sheet.tsx
import type { HTMLAttributes, ReactNode } from 'react';

import { renderChordproAst } from './chordpro-jsx';
import {
  type ChordRenderFormat,
  type ChordRenderOptions,
  type ChordWasmLoader,
  useChordRender,
} from './use-chord-render';
import {
  type ChordproWasmLoader,
  useChordproAst,
} from './use-chordpro-ast';

/** Props accepted by {@link ChordSheet}. */
export interface ChordSheetProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** ChordPro source to render. */
  source: string;
  /** Semitone transposition offset forwarded to the renderer. */
  transpose?: number;
  /**
   * Configuration preset name (e.g. `"guitar"`, `"ukulele"`) or an
   * inline RRJSON configuration string.
   */
  config?: string;
  /**
   * Render target. `"html"` (default) produces ChordPro's HTML
   * output and renders via `dangerouslySetInnerHTML`; `"text"`
   * produces plain chords-above-lyrics text which renders inside a
   * `<pre>` with no HTML parsing. Both outputs come from the
   * `@chordsketch/wasm` renderer, which the host trusts — no user
   * HTML is ever injected.
   */
  format?: ChordRenderFormat;
  /**
   * Optional content shown while WASM is initialising or a render
   * is in flight. Defaults to the last successful output so the
   * preview does not blank during edits; pass `null` to hide.
   */
  loadingFallback?: ReactNode;
  /**
   * Optional render prop that takes over when a parse or render
   * error occurs. Receives the `Error` instance; return any
   * `ReactNode`. Defaults to a minimal `role="alert"` div showing
   * the error message. Pass `null` to hide errors entirely (useful
   * when the host surfaces them via a toast or inline banner
   * alongside the stale output).
   */
  errorFallback?: ((error: Error) => ReactNode) | null;
  /**
   * Test-only WASM loader override. Production callers never need
   * to supply this — the default lazy-loads `@chordsketch/wasm`.
   *
   * @internal
   */
  wasmLoader?: ChordWasmLoader;
}

function defaultErrorFallback(error: Error): ReactNode {
  return (
    <div role="alert" className="chordsketch-sheet__error">
      {error.message}
    </div>
  );
}

/**
 * Flagship render component for the library. Renders ChordPro
 * source via `@chordsketch/wasm` and memoises the result against
 * `(source, format, transpose, config)` so re-renders without
 * input changes do not re-parse.
 *
 * ```tsx
 * <ChordSheet source={chordproSource} transpose={0} />
 * ```
 *
 * Render path (per ADR-0017):
 * - `format="html"` parses with `parseChordpro` and renders the
 *   AST directly via the chordpro-jsx walker — pure React DOM,
 *   no HTML-string injection, no `<style>` block on the React
 *   surface.
 * - `format="text"` retains the wasm `render_text` path because
 *   ChordPro's text rendering is column-aligned plain output the
 *   AST walker would have to re-derive.
 *
 * Error handling: parse or render errors surface via the
 * `errorFallback` prop (default: inline `role="alert"`); the
 * component does not throw. The previous successful output stays
 * visible while a transient error shows alongside, so a
 * half-typed edit does not blank the preview.
 */
export function ChordSheet({
  source,
  transpose,
  config,
  format = 'html',
  loadingFallback,
  errorFallback = defaultErrorFallback,
  wasmLoader,
  className,
  ...divProps
}: ChordSheetProps): JSX.Element {
  const wrapperClass = ['chordsketch-sheet', className].filter(Boolean).join(' ');

  if (format === 'text') {
    return (
      <ChordSheetTextBranch
        source={source}
        transpose={transpose}
        config={config}
        loadingFallback={loadingFallback}
        errorFallback={errorFallback}
        wasmLoader={wasmLoader}
        wrapperClass={wrapperClass}
        divProps={divProps}
      />
    );
  }

  return (
    <ChordSheetAstBranch
      source={source}
      transpose={transpose}
      config={config}
      loadingFallback={loadingFallback}
      errorFallback={errorFallback}
      wasmLoader={wasmLoader as unknown as ChordproWasmLoader | undefined}
      wrapperClass={wrapperClass}
      divProps={divProps}
    />
  );
}

interface BranchProps {
  source: string;
  transpose: number | undefined;
  config: string | undefined;
  loadingFallback: ReactNode | undefined;
  errorFallback: ((error: Error) => ReactNode) | null;
  wrapperClass: string;
  divProps: Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'className'>;
}

function ChordSheetTextBranch({
  source,
  transpose,
  config,
  loadingFallback,
  errorFallback,
  wasmLoader,
  wrapperClass,
  divProps,
}: BranchProps & { wasmLoader: ChordWasmLoader | undefined }): JSX.Element {
  const renderOptions: ChordRenderOptions = { transpose, config };
  const { output, loading, error } = useChordRender(source, 'text', renderOptions, wasmLoader);
  const errorNode = error !== null && errorFallback !== null ? errorFallback(error) : null;

  if (output === null) {
    return (
      <div {...divProps} className={wrapperClass} aria-busy={loading || undefined}>
        {errorNode}
        {loading && loadingFallback !== undefined ? loadingFallback : null}
      </div>
    );
  }

  return (
    <div {...divProps} className={wrapperClass} aria-busy={loading || undefined}>
      {errorNode}
      <pre className="chordsketch-sheet__text">{output}</pre>
    </div>
  );
}

function ChordSheetAstBranch({
  source,
  transpose,
  config,
  loadingFallback,
  errorFallback,
  wasmLoader,
  wrapperClass,
  divProps,
}: BranchProps & { wasmLoader: ChordproWasmLoader | undefined }): JSX.Element {
  const { ast, loading, error } = useChordproAst(source, { transpose, config }, wasmLoader);
  const errorNode = error !== null && errorFallback !== null ? errorFallback(error) : null;

  if (ast === null) {
    return (
      <div {...divProps} className={wrapperClass} aria-busy={loading || undefined}>
        {errorNode}
        {loading && loadingFallback !== undefined ? loadingFallback : null}
      </div>
    );
  }

  // AST walker emits a `<div class="song">` root matching the
  // `chordsketch-render-html` DOM contract so existing CSS keeps
  // working unchanged. Pure React reconciliation owns the tree
  // — no innerHTML escape hatch on this surface.
  return (
    <div {...divProps} className={wrapperClass} aria-busy={loading || undefined}>
      {errorNode}
      <div className="chordsketch-sheet__content">{renderChordproAst(ast)}</div>
    </div>
  );
}

// packages/svelte/src/ChordSheet.svelte
<!--
@component
Flagship render component for the library. Renders ChordPro source
via `@chordsketch/wasm` and re-renders only when `source`,
`transpose`, `config` or `format` changes.

```svelte
<ChordSheet source={chordpro} transpose={2} />
```

Render path:
- `format="html"` injects the renderer's body-only fragment
  (`render_html_body`) into a `.chordsketch-sheet__content` wrapper,
  and injects the renderer's own stylesheet once — rewritten so
  every rule only matches inside that wrapper (see
  `renderer-css.ts`). The fragment is produced by our own Rust
  renderer from a fixed template, so injecting it as HTML is safe.
- `format="text"` renders the column-aligned plain output inside a
  `<pre>` with no HTML parsing.

Error handling: parse or render errors render through the `error`
snippet (default: an inline `role="alert"`); the component does not
throw. The previous successful output stays visible while a
transient error shows alongside, so a half-typed edit does not blank
the preview.

### Snippets

- `loading` — shown while WASM initialises and no output exists yet.
  Omit to render nothing.
- `error` — receives the `Error`. Pass an empty snippet to suppress
  the inline error entirely (e.g. when the host surfaces it through
  a toast).
-->
<script lang="ts">
  import { untrack, type Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  import { SHEET_CONTENT_CLASS, ensureRendererCss } from './renderer-css';
  import {
    useChordRender,
    type ChordRenderFormat,
    type ChordWasmLoader,
  } from './use-chord-render.svelte';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    /** ChordPro source to render. */
    source: string;
    /** Semitone transposition offset forwarded to the renderer. */
    transpose?: number;
    /**
     * Configuration preset name (e.g. `"guitar"`, `"ukulele"`) or
     * an inline RRJSON configuration string.
     */
    config?: string;
    /** Render target. Defaults to `"html"`. */
    format?: ChordRenderFormat;
    /** Shown while the WASM module loads and no output exists yet. */
    loading?: Snippet;
    /** Renders a render / init failure. Receives the `Error`. */
    error?: Snippet<[Error]>;
    /**
     * Test-only WASM loader override. Production callers never need
     * to supply this — the default lazy-loads `@chordsketch/wasm`.
     *
     * @internal
     */
    wasmLoader?: ChordWasmLoader;
  }

  let {
    source,
    transpose = undefined,
    config = undefined,
    format = 'html',
    loading: loadingSnippet = undefined,
    error: errorSnippet = undefined,
    wasmLoader = undefined,
    ...rest
  }: Props = $props();

  // Read once, deliberately: the loader identity keys the module
  // cache in `wasm-loader.ts`, so swapping it mid-life would
  // instantiate a second WASM module rather than re-render. Same
  // snapshot semantics as the React / Vue bindings.
  const loader = untrack(() => wasmLoader);

  const render = useChordRender(
    () => source,
    () => ({ format, transpose, config }),
    loader,
  );

  // The HTML fragment carries no styling of its own; pair it with
  // the renderer's stylesheet, scoped to this component's wrapper.
  // Runs once per (transpose, config) pair — `ensureRendererCss`
  // dedupes against what is already in the document.
  $effect(() => {
    if (format !== 'html') return;
    void ensureRendererCss({ transpose, config }, loader);
  });
</script>

<div
  {...rest}
  class={['chordsketch-sheet', rest.class]}
  aria-busy={render.loading ? 'true' : undefined}
>
  {#if render.error !== null}
    {#if errorSnippet}
      {@render errorSnippet(render.error)}
    {:else}
      <div role="alert" class="chordsketch-sheet__error">{render.error.message}</div>
    {/if}
  {/if}

  {#if render.output === null}
    {#if render.loading && loadingSnippet}
      {@render loadingSnippet()}
    {/if}
  {:else if format === 'text'}
    <pre class="chordsketch-sheet__text">{render.output}</pre>
  {:else}
    <div class={SHEET_CONTENT_CLASS}>
      {@html render.output}
    </div>
  {/if}
</div>
